### ISSUE TITLE
Roadmap for Strata

### ISSUE THREAD

**Issue by anantnrg** [StrataWM/strata#75]
This is a list of things/features/bug fixes to be implemented before the first stable release of Strata. Figured it was easier to keep track this way.

- [ ] Complete [Lua](https://www.lua.org/) config implementation using [Piccolo](https://github.com/kyren/piccolo) (Most of the implementation is done thanks to @MurdeRM3L0DY)
- [ ] Implement UDEV-TTY backend (@anantnrg)
- [ ] Fix bugs with tiling and maybe use/make a layout library like [Taffy](https://github.com/dioxus/taffy)
- [ ] Add window rules
- [ ] Add floating windows (could depend on first fixing the tiling)
